### ISSUE TITLE
Can't watch livestream on LTT OG Tier

### ISSUE THREAD

**Issue by DarkStarr** [bmlzootown/Hydravion-AndroidTV#22]
The Android TV app claims I can't watch the livestream on the cheapest tier but I used the Android TV app on this same tier just a few weeks ago and it works fine on the site.

The Roku app also currently works fine for the livestream though every other video crashes the app.

**Comment by bmlzootown** [comment]
> The Android TV app claims I can't watch the livestream on the cheapest tier but I used the Android TV app on this same tier just a few weeks ago and it works fine on the site.

Not sure what happened, but I was able to reproduce the described behavior by installing the latest release that was posted to Github. I could not, however, replicate the issue when debugging via Android Studio, nor could I reproduce it after recompiling the APK and installing that way.

Went ahead and replaced the latest release (https://github.com/bmlzootown/Hydravion-AndroidTV/releases/tag/v1.4.7). 
Let me know if this fixes that issue for you.

> The Roku app also currently works fine for the livestream though every other video crashes the app.

I'm not able to recreate this issue at all, but that might be due to recent API changes. The official release on the store won't get the update that fixes it until Monday (due to the way Roku schedules releases), but you can add the beta channel via vanity code (https://my.roku.com/account/add/TNCPHK5) and use that until the official update goes live.

**Comment by DarkStarr** [comment]
The new apk seemed to fix the issue. As for the Roku issue I figured that was due to the lag on the store but I thought it was interesting the livestream worked there but not on the Android TV app.
