### ISSUE TITLE
Login looping

### ISSUE THREAD

**Issue by phpandrew** [bmlzootown/Hydravion-AndroidTV#35]
### Checklist before submitting a bug report

- [X] This bug/issue is affecting the Hydravion for AndroidTV
- [X] I've searched for existing [issues](https://github.com/bmlzootown/Hydravion-AndroidTV/issues?q=is:issue) and found no duplicates
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

### Device Manufacturer & Model

Nvidia Shield 

### Android TV OS Version

Android 14

### Hydravion Version

1.5.3

### Whom you are subscribed to?

LTT

### Error/Issue Details

Opening the app prompts me to login.
Once I enter my information it prompts me to re-open Hydration to login again! Because my session has expired.

This is a continuous loop asking me to login

**Comment by bmlzootown** [comment]
This issue was recently reported for the previous version in the Discord server. At some point, they changed the "set-cookie" header to "Set-Cookie", so a simple case-insensitive check appeared to fix it on my end. That said, you appear to be running the latest version which was pushed to fix said issue. 

When the application is grabbing subscriptions (using the `refreshSubscriptions()` method), it checks two things -- the first is to see if the returned `subscriptions` object is null, and the second is to check to see that the `subscriptions` object isn't empty. The former, when it returns a null object, is the only time it should ever throw the `Session Expired` dialog and prompt you to re-open/relog -- this means that something has gone wonky when trying to query who all you're subscribed to. I myself am also subscribed to LTT, but it has no issue loading for me.

Since I can't seem to replicate this on my end, if you're able/willing, login to the Floatplane site in your browser, navigate to the following page (this is the API call to get subscriptions, which is what's causing the error in the app) and either post the JSON it returns or send it to me via Discord DM/email: https://www.floatplane.com/api/v3/user/subscriptions

**Comment by phpandrew** [comment]
I apologize, I thought the app was updated to 1.5.3, but it was still 1.5.2.

I updated the app and it works now. I thought I had updated it, but I could have confused this with my second shield.
Sorry, I will mark this as resolved.
