### ISSUE TITLE
4K Video Playback Sometimes Fails

### ISSUE THREAD

**Issue by bmlzootown** [bmlzootown/Hydravion-AndroidTV#8]
As stated, 4K playback sometimes fails seemingly only for LTT-specific videos. TQ, TL, MA, and other channels don't seem to be affected. 

As has been mentioned in Discord, Floatplane's own Android app uses a combination of React/JS and ExoPlayer, the latter of which we also use for AndroidTV.

If anyone has any thoughts/suggestions, I'm all ears (or eyes, rather). I'm at a loss as of right now.

**Comment by Ulrar** [comment]
If when you say "fail" you mean simply doesn't start with no error then I can confirm, I have that issue on an Nvidia shield. Clicking a video does nothing at all.

**Comment by Maelstrom96** [comment]
We're already aware of the issue related to 4K on some particular devices. The reason the playback is failing is because the devices fail to decode the video files because we're out of the specs they support. This is because of the resolution we output for LTT videos and their weird video ratio. We'll likely change the transcoding resolution for new 4k videos soon. This is not something that can actually be fixed by the client, other than have the client fallback to a lower rendition when the player gets a decoding failure.

**Comment by Ulrar** [comment]
That's good to hear. I personally stopped my subscription since casting seems to cap out at 1080p and this client wasn't working for 4k, I just ended right back on youtube. Keeping an eye on this since I'd happily subscribe again if 4k started working though.

**Comment by avmavairborne** [comment]
Ah, I see. It's 4320 x 2160, not 3840 x 2160, thus exceeding the TV's max resolution! Thanks for the insight!

**Comment by nwgat** [comment]
yeah some videos have weird resolutions/aspect and they are encoded at higher profile levels than what some standalone hardware devices can decode

**Comment by Maelstrom96** [comment]
Hey, just to say that newer videos should be properly boxed to a resolution compatible with level 5.1 or 4.0, which should make playback better overall. We might re-transcode older videos to fix their resolution, but for now, only newer LTT 4K videos will be fixed.

**Comment by AvMavs** [comment]
Thanks Ajax!

**Comment by bmlzootown** [comment]
Given the update, going to close this.
